name: Upload Files
description: |
  Upload files with given pattern from a path to the server. The target to upload
  files to is defined with a combination of `base` and `folder` which will be the
  format of `<upload-to-base>/<upload-to-folder>`.

inputs:
  upload-from:
    description: "Path on disk to upload files from"
    required: true
    default: "/build/publish/"
  upload-pattern:
    description: "File pattern to use to upload from"
    required: true
    default: "*"
  upload-to-base:
    description: "Base path on the server to upload to"
    required: true
    default: "/opt/archives/packages/"
  upload-to-folder:
    description: "Name of the folder to upload into in 'upload-to-base'"
    required: true

runs:
  using: composite
  steps:
    - name: Upload Files
      shell: bash
      run: |
        set -e

        UPLOAD_FROM="${{ inputs.upload-from }}"
        UPLOAD_TO_BASE="${{ inputs.upload-to-base }}"
        UPLOAD_TO_FOLDER="${{ inputs.upload-to-folder }}"

        rsync \
          -avzhH \
          --ignore-missing-args \
          --mkpath \
          ${UPLOAD_FROM%/}/${{ inputs.upload-pattern }} \
          ${{ env.server-username }}@${{ env.server-address }}:${UPLOAD_TO_BASE%/}/${UPLOAD_TO_FOLDER%/}/
