name: Import GPG Key
description: |
  Import given GPG private key with its associated email and full name.

inputs:
  gpg-key:
    description: "GPG Private Key to import"
    required: true
  gpg-email:
    description: "Email ID associated with the GPG Key"
    required: true
    default: "regolith.linux@gmail.com"
  gpg-name:
    description: "Full Name associated with the GPG Key"
    required: true
    default: "Regolith Linux"

outputs:
  gpg-email:
    description: "Email ID associated with the GPG Key"
    value: ${{ inputs.gpg-email }}
  gpg-name:
    description: "Full Name associated with the GPG Key"
    value: ${{ inputs.gpg-name }}

runs:
  using: composite
  steps:
    - name: Import GPG Key
      shell: bash
      run: |
        export DEBEMAIL="${{ inputs.gpg-email }}"
        export DEBFULLNAME="${{ inputs.gpg-name }}"

        printf "${{ inputs.gpg-key }}" | base64 --decode > /home/regolith/.gnupg/private.key
        chmod 600 /home/regolith/.gnupg/*

        gpg --batch --import /home/regolith/.gnupg/private.key
