name: Rebuild Sources
description: |
  Rebuild the source files.

  The `.dsc` and `.debian.tar.xz` files will be rebuilt out of exisiting `.orig.tar.gz`
  file which previously was repacked without `/debian` folder in it.

  This will ensure one single .orig.tar.gz file can be used for all the packages of the
  same version and same component of different codenames.

inputs:
  pull-from-base:
    description: "Base path on the server to pull packages from"
    required: true
    default: "/opt/archives/workspace/"
  push-to-base:
    description: "Base path on the server to push rebuils sources to"
    required: true
    default: "/opt/archives/packages/"
  workspace-subfolder:
    description: "workspace-subfolder is the name of the folder to use inside 'pull-from-base' and 'push-to-base'"
    required: true
  only-distro:
    description: "A filter to only rebuild sources for this distro"
    required: false
  only-codename:
    description: "A filter to only rebuild sources for this codename"
    required: false
  only-component:
    description: "A filter to only rebuild sources for this component"
    required: false
  only-package:
    description: "A filter to only rebuild sources for this package"
    required: false
  gpg-email:
    description: "Email ID associated with the GPG Key"
    required: true
    default: "regolith.linux@gmail.com"
  gpg-name:
    description: "Full Name associated with the GPG Key"
    required: true
    default: "Regolith Linux"

runs:
  using: composite
  steps:
    - name: Get Voulage
      id: voulage
      uses: regolith-linux/actions/get-voulage@main

    - name: Prepare Source Files
      shell: bash
      run: |
        WORKSPACE_BASE_PATH="${{ inputs.pull-from-base }}"
        WORKSPACE_FOLDER="${{ inputs.workspace-subfolder }}"

        WORKSPACE_FOLDER_PATH="${WORKSPACE_FOLDER%/}/run-${{ github.run_id }}/"

        ssh ${{ env.server-username }}@${{ env.server-address }} "get-published-sources.sh --workspace-path \"${WORKSPACE_BASE_PATH}\" --workspace-folder \"${WORKSPACE_FOLDER_PATH}\""

    - name: Pull Source Files
      shell: bash
      run: |
        PULL_FROM_BASE="${{ inputs.pull-from-base }}"
        PULL_FROM_FOLDER="${{ inputs.workspace-subfolder }}"
        PULL_FULL_PATH="${PULL_FROM_BASE%/}/${PULL_FROM_FOLDER%/}/run-${{ github.run_id }}/"

        echo "::group::Downloading source files..."
        rsync \
          -avzh \
          --exclude="*.*/" \
          --include="*/" \
          --include="*.orig.tar.gz" \
          --include="*.debian.tar.xz" \
          --include="*.tar.xz" \
          --include="*.diff.gz" \
          --exclude="*" \
          ${{ env.server-username }}@${{ env.server-address }}:${PULL_FULL_PATH} \
          /build/workspace/
        echo "::endgroup::"

    - name: Rebuild Sources
      shell: bash
      env:
        WORKSPACE_PATH: "/build/workspace/"
        VOULAGE_PATH: "${{ steps.voulage.outputs.path }}"

        ONLY_DISTRO: "${{ inputs.only-distro }}"
        ONLY_CODENAME: "${{ inputs.only-codename }}"
        ONLY_COMPONENT: "${{ inputs.only-component }}"
        ONLY_PACKAGE: "${{ inputs.only-package }}"

        GPG_EMAIL: "${{ inputs.gpg-email }}"
        GPG_NAME: "${{ inputs.gpg-name }}"
      run: $GITHUB_ACTION_PATH/entrypoint.sh

    - name: Upload Source Files
      uses: regolith-linux/actions/upload-files@main
      env:
        server-address: "${{ env.server-address }}"
        server-username: "${{ env.server-username }}"
      with:
        upload-from: "/build/workspace/"
        upload-pattern: "*"
        upload-to-base: "${{ inputs.push-to-base }}"
        upload-to-folder: "${{ inputs.workspace-subfolder }}"

    - name: Cleanup Workspace
      shell: bash
      run: |
        WORKSPACE_BASE_PATH="${{ inputs.pull-from-base }}"
        WORKSPACE_FOLDER="${{ inputs.workspace-subfolder }}"

        WORKSPACE_FOLDER_PATH="${WORKSPACE_FOLDER%/}/run-${{ github.run_id }}/"

        ssh ${{ env.server-username }}@${{ env.server-address }} "cleanup-workspace.sh --workspace-path \"${WORKSPACE_BASE_PATH}\" --workspace-folder \"${WORKSPACE_FOLDER_PATH}\""
