name: Build Package
description: |
  Build a package for speficied distro/codename/stage triplet. It uses package
  name, package repo, and package ref to checkout the code.

inputs:
  only-build:
    description: "Only build indicator, if set to false don't sign nor publish the package"
    required: true
    default: "false"
  name:
    description: "Name of the package to build"
    required: true
  distro:
    description: "Target Distro to build the package for (debian, ubuntu)"
    required: true
  codename:
    description: "Target Codename to build the package for (e.g. focal, bullseye)"
    required: true
  stage:
    description: "Regolith release stage (e.g. unstable, testing, stable)"
    required: true
  suite:
    description: "Regolith package archive suite (e.g. unstable, testing, stable)"
    required: true
  component:
    description: "Regolith package archive component (e.g. main, v3.2, v3.1)"
    required: true
  arch:
    description: "Regolith architectures (amd64, arm64)"
    required: true
  gpg-email:
    description: "Email ID associated with the GPG Key"
    required: true
    default: "regolith.linux@gmail.com"
  gpg-name:
    description: "Full Name associated with the GPG Key"
    required: true
    default: "Regolith Linux"

outputs:
  publish-path:
    description: "The path on disk that packages are published to"
    value: ${{ steps.build.outputs.publish-path }}
  buildlog-path:
    description: "The path on disk that buildlogs are saved to"
    value: ${{ steps.build.outputs.buildlog-path }}

runs:
  using: composite
  steps:
    - name: Get Voulage
      id: voulage
      uses: regolith-linux/actions/get-voulage@main

    - name: Build Package
      id: build
      shell: bash
      env:
        WORKSPACE_PATH: "${{ github.workspace }}"
        VOULAGE_PATH: "${{ steps.voulage.outputs.path }}"

        BUILD_ONLY: "${{ inputs.only-build }}"

        PACKAGE_NAME: "${{ inputs.name }}"
        DISTRO: "${{ inputs.distro }}"
        CODENAME: "${{ inputs.codename }}"
        STAGE: "${{ inputs.stage }}"
        SUITE: "${{ inputs.suite }}"
        COMPONENT: "${{ inputs.component }}"
        ARCH: "${{ inputs.arch }}"

        GPG_EMAIL: "${{ inputs.gpg-email }}"
        GPG_NAME: "${{ inputs.gpg-name }}"
      run: $GITHUB_ACTION_PATH/entrypoint.sh
