name: Setup SSH
description: |
  Setup SSH agent and add server keyscan to the known_hosts file.

inputs:
  ssh-host:
    description: "Server IP address or FQDN"
    required: true
  ssh-key:
    description: "Server SSH private key"
    required: true

runs:
  using: composite
  steps:
    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-key }}

    - name: Generate Known Hosts
      shell: bash
      run: ssh-keyscan -H ${{ inputs.ssh-host }} >> /home/regolith/.ssh/known_hosts
