name: Update Manifest
description: |
  Update and upload the manifest file for the package that is just built with
  package name, repo, ref, and sha.

inputs:
  name:
    description: "Name of the package to update the manifest for"
    required: true
  repo:
    description: "Public git repository URL of the package"
    required: true
  ref:
    description: "Git repository ref that the package was built at (e.g. branch, tag, or hash)"
    required: true
  sha:
    description: "Commit SHA of the repository that the package was built at"
    required: true
  matrix:
    description: "Encoded JSON list of target distro, codename, and architecture"
    required: true
  suite:
    description: "Regolith package archive suite (e.g. unstable, testing, stable)"
    required: true
  component:
    description: "Regolith package archive component (e.g. main, v3.2, v3.1)"
    required: true

runs:
  using: composite
  steps:
    - name: Get Voulage
      id: voulage
      uses: regolith-linux/actions/get-voulage@main

    - name: Update Manifest
      shell: bash
      env:
        VOULAGE_PATH: "${{ steps.voulage.outputs.path }}"

        NAME: "${{ inputs.name }}"
        REPO: "${{ inputs.repo }}"
        REF: "${{ inputs.ref }}"
        SHA: "${{ inputs.sha }}"
        MATRIX: "${{ inputs.matrix }}"
        SUITE: "${{ inputs.suite }}"
        COMPONENT: "${{ inputs.component }}"
      run: $GITHUB_ACTION_PATH/entrypoint.sh

    - name: Push Manifest Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        repository: "${{ steps.voulage.outputs.path }}"
        branch: "main"
        file_pattern: "*"
        commit_message: "chore: update ${{ inputs.suite }} manifest for ${{ inputs.name }}"
        commit_user_name: regolith-bot
        commit_user_email: bot@regolith-desktop.com
        commit_author: "regolith-bot <bot@regolith-desktop.com>"
