name: Build Matrix of Supported OS
description: |
  Build a matrix of currently supported distros and codenames in encoded JSON list
  format. The list is being built out of `stage/unstable` folder of voulage repository
  at https://github.com/regolith-linux/voulage/

outputs:
  includes:
    description: "The serialized JSON list of matrix include items"
    value: ${{ steps.builder.outputs.includes }}

runs:
  using: composite
  steps:
    - name: Get Voulage
      shell: bash
      run: $GITHUB_ACTION_PATH/get-voulage.sh

    - name: Matrix Includes Builder
      id: builder
      shell: bash
      run: $GITHUB_ACTION_PATH/build-matrix.sh
