name: Check Workflow files

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "test-desktop/**"
  push:
    branches:
      - main
    paths:
      - "test-desktop/**"

jobs:
  workflow-files:
    runs-on: ubuntu-24.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3

      - name: Generate workflow files
        run: go run test-desktop/main.go

      - name: Check workflow files
        run: test -z "$(git status --porcelain)" || exit 1
