name: Check Workflow files

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - "test-desktop/**"

jobs:
  workflow-files:
    runs-on: ubuntu-24.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.ORG_BROADCAST_TOKEN2 }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3

      - name: Generate workflow files
        run: go run test-desktop/main.go

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_BROADCAST_TOKEN2 }}
        with:
          file_pattern: ".github/workflows/"
          commit_message: "chore: auto generate test-...-repo workflow files"
          commit_user_name: regolith-ci-bot
          commit_user_email: bot@regolith-desktop.com
          commit_author: "regolith-ci-bot <bot@regolith-desktop.com>"
