name: Test Runners

on:
  push:
    branches-ignore:
      - main

jobs:
  matrix-builder:
    runs-on: regolith-amd64
    # container: "ghcr.io/regolith-linux/ci-ubuntu:noble-amd64"
    outputs:
      includes: ${{ steps.builder.outputs.includes }}
    steps:
      - name: Build Matrix
        id: builder
        uses: regolith-linux/actions/build-matrix@main
        with:
          name: "${{ github.event.repository.name }}"
          ref: "main"
          arch: "amd64"
          stage: "unstable"

  # test:
  #   runs-on: ubuntu-24.04
  #   container: "ubuntu:oracular"
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - run: |
  #         pwd
  #         ls -la
  #         touch $(pwd)/in-pwd
  #         ls -la
  #         echo "==================================="
  #         WORKSPACE_ROOT_PATH=$(realpath "$(realpath "$(pwd)")/../")
  #         echo $WORKSPACE_ROOT_PATH
  #         ls -la "$WORKSPACE_ROOT_PATH"
  #         touch $WORKSPACE_ROOT_PATH/in-workspace
  #         ls -la "$WORKSPACE_ROOT_PATH"
  #     - run: |
  #         pwd
  #         ls -la
  #         echo "==================================="
  #         WORKSPACE_ROOT_PATH=$(realpath "$(realpath "$(pwd)")/../")
  #         echo $WORKSPACE_ROOT_PATH
  #         ls -la "$WORKSPACE_ROOT_PATH"

  build:
    runs-on: ["regolith-${{ matrix.arch }}"]
    # runs-on: ubuntu-24.04
    # runs-on: [self-hosted, Linux, "${{ matrix.arch }}", noble] 
    needs: matrix-builder
    container: "ghcr.io/regolith-linux/ci-${{ matrix.distro }}:${{ matrix.codename }}-${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.matrix-builder.outputs.includes) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Building ${{ matrix.distro }}/${{ matrix.codename }} (arch=${{ matrix.arch }})"
          uname -a
          cat /etc/*-release

      # - name: Build Package
      #   uses: regolith-linux/actions/build-package@enhance-build-matrix
      #   with:
      #     name: "${{ github.event.repository.name }}"
      #     distro: "${{ matrix.distro }}"
      #     codename: "${{ matrix.codename }}"
      #     stage: "unstable"
      #     suite: "unstable"
      #     component: "main"
      #     arch: "${{ matrix.arch }}"
      #     gpg-key: "${{ secrets.PACKAGE_PRIVATE_KEY2 }}"
