name: Update workflow files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'
  pull_request:
  push:
    branches:
      - main

jobs:
  workflow-files:
    runs-on: ubuntu-24.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3

      - name: Generate workflow files
        run: go run main.go

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_pattern: '.github/workflows/*.yml'
          commit_message: "chore: update ci and test workflow files"
